// ClaudeCode 2026-08-25 — EMBEDDED COPY of VAI/onboarding/vai-lsp-guide.md
// (platform repo). Embedded rather than read from disk because Connect deploys
// from the MCP repo only — that folder does not exist in the container. Served
// verbatim at GET /start/r/<id>/vai-lsp-guide.md so the teammate's Claude can
// fetch it straight off the start page. Update this file when the source guide
// changes; it is documentation, not a secret.
// ClaudeCode 2026-08-27 11:06 AM PDT — RE-EMBEDDED from the current source file.
// The previous embed was stale (it still named vai/north-star.md and a third
// document that no longer exists) and predates the new "If a sign-in tab opens"
// section, which is the point of this pass: a connector sign-in that opens during
// MCP boot must be announced by name, not discovered.
export const VAI_LSP_GUIDE_MD = "# VAI \u00d7 LifeSpace tools \u2014 operating guide (import from your CLAUDE.md: @vai-lsp-guide.md)\n\nYou are connected to the **VAI workspace** on the LifeSpace platform (LSP) via **LSP Tools** (the `lsp_*` MCP tools).\n\n## First, every session\n1. Run `lsp_trust_whoami` \u2014 confirm tenant is VAI.\n2. Your two operating documents live in Knowledge \u2014 read them before substantive work:\n   - `ai-documentation/vai-orientation.md` \u2014 VAI Orientation \u2014 the rules, terms, and operating practices\n   - `ai-documentation/lifespace-platform-module-reference.md` \u2014 every platform module you can build on (platform-maintained)\n   (`lsp_knowledge_read` with those paths.)\n\n## Non-negotiables (full versions in the Orientation doc)\n- Client data lives in that client's sub-tenant. Never cross tenants. Ask if unsure.\n- AI drafts; a human sends. Never bypass an approval gate.\n- Never touch: wires, funds, MLS credentials, new-lead outreach, price/terms advice.\n- Credentials only via Keys. Never in chat, files, or prompts.\n- VAI-owned skills and data use the `vai-` prefix.\n\n## If a sign-in tab opens\n- A LifeSpace sign-in page can open in the browser **by itself** while this session starts up \u2014 before you are awake. Say so in your **first message**, and name the tenant shown on that page so the person knows which one it belongs to.\n- The link to open it again is `auth_url` in `.claude/lsp-oauth-pending.json` in this folder. Hand over the URL; never click through a sign-in for someone.\n\n## Default behaviors\n- Track work in Tickets/Projects; save decisions to Memory; file documents in Knowledge \u2014 as they happen, not at session end.\n- Search before creating (Knowledge, Skills) \u2014 don't duplicate.\n- Verify writes by reading them back before reporting done.\n";
export const VAI_GUIDE_FILENAME = 'vai-lsp-guide.md';
